config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "profile", to: "users#profile"
  get "users/:id/edit", to: "users#edit", as: :edit_user

  resources :users, only: :index

  resources :bets, except: [:new, :edit] do
    collection do
      get "multiform_step_1"
    end
    get "multiform_step_2"
    get "multiform_step_3"
    get "resolve"
    patch "set_result"

    post 'accept'
    post 'deny'
  end

  get "my_bets", to: "bets#my_bets"
  get "around_me", to: "bets#around_me"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :tag, optional: true
  belongs_to :user
  belongs_to :opponent, class_name: "User"
  belongs_to :winner, class_name: "User", optional: true

  validates :name, presence: true, length: { maximum: 16 }

  # validates :stake, presence: true
  # validates :location, presence: true
  # validates :privacy, presence: true

  enum :status, {
    pending: 0,
    active: 1,
    finished: 2,
    rejected: 3
  }

  geocoded_by :location, latitude: :latitude, longitude: :longitude
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/tag.rb
class Tag < ApplicationRecord
  CATEGORIES = ["Sports", "Video games & e-sports", "Challenges", "Fact-check", "Cards & board games", "Other ;)"]

  validates :name, inclusion: CATEGORIES

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_one_attached :photo
  has_many :bets, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :location, latitude: :latitude, longitude: :longitude
  after_validation :geocode, if: :will_save_change_to_location?

  def active_bets
    Bet.where("(user_id = :user OR opponent_id = :user) AND status = 1", user: self.id)
  end

  def past_bets
    Bet.where("(user_id = :user OR opponent_id = :user) AND status = 2", user: self.id)
  end

  def sent_pending_bets
    Bet.where("user_id = :user AND status = 0", user: self.id)
  end

  def received_pending_bets
    Bet.where("opponent_id = :user AND status = 0", user: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :name, :location])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo, :name, :location])
  end

  def default_url_options
    { host: ENV["www.dare2bet.me"] || "localhost:3000" }
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, only: [:multiform_step_2, :multiform_step_3, :update, :show, :accept, :deny]

  def index
    @bets = Bet.all.order(end_time: :asc).where(status: 1)
  end

  def show
  end

  def around_me
    @bets = Bet.all.order(end_time: :asc).where(status: 1)
    @markers = @bets.geocoded.map do |bet|
      {
        lat: bet.latitude,
        lng: bet.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {bet: bet})
      }
    end
  end

  def multiform_step_1
    @bet = Bet.new
  end

  def create
    @bet = Bet.new(bet_params)
    @bet.user = current_user
    if @bet.save
      redirect_to bet_multiform_step_2_path(@bet)
    else
      render :multiform_step_1, status: :unprocessable_entity
    end
  end

  def multiform_step_2
  end

  def multiform_step_3
  end

 def update
  @bet.update(bet_params)
  if params[:step_2]
    redirect_to bet_multiform_step_3_path(@bet)
  else
    redirect_to bet_path(@bet)
  end
 end

  def edit
  end

  def resolve
    @bet = Bet.find(params[:bet_id])
  end

  def set_result
    @bet = Bet.find(params[:bet_id])
    if @bet.update(bet_params)
      @bet.finished!
      redirect_to bet_path(@bet, bet_settled: true)
    else
      render :resolve, status: :unprocessable_entity
    end
  end


  def destroy
    @bet = Bet.find(params[:id])
    @bet.destroy
    if request.referrer == my_bets_url
      redirect_to my_bets_path, notice: "Bet was successfully cancelled."
    else
      redirect_to bets_path, notice: "Bet was successfully cancelled."
    end

  end

  def my_bets
    @active_bets = current_user.active_bets
    @past_bets = current_user.past_bets
  end

  def accept
    @bet.active!

    redirect_to bet_path(@bet), notice: "You accepted the bet #{@bet.name}!"
  end

  def deny
    @bet.rejected!

    redirect_to profile_path, notice: "You rejected the bet #{@bet.name}"
  end

  private

  def bet_params
    params.require(:bet).permit(:name, :stake, :location, :end_time, :privacy, :status, :tag_id, :outcome, :opponent_id, :winner_id)
  end

  def set_bet
    if params[:bet_id]
      @bet = Bet.find(params[:bet_id])
    else
      @bet = Bet.find(params[:id])
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @bets = Bet.all.order(end_time: :asc).where(status: 1)
    redirect_to bets_path if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where("name iLIKE '%#{params[:s]}%'")
    render json: { items: @users }
  end

  def show
    @user = User.find(params[:id])
  end

  def profile
    @sent_pending_bets = current_user.sent_pending_bets
    @received_pending_bets = current_user.received_pending_bets
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/bets/_bet_card.html.erb
<div class="mt-5" data-controller="<%= "confetti" if bet.finished? && action_name == "show" %>">
  <div class="card border-0 position-relative <%= "expired-card" if bet.finished? && action_name != "show" %>">
    <%= link_to bet_path(bet), class: "text-decoration-none" do %>
      <div class="card-body pt-4 <%= "rounded-top-4 rounded-0" if action_name == "show" %>">
        <div class="row">
          <div class="col-5 d-flex align-items-center justify-content-center gap-2">
            <div class="position-relative text-center<%= bet.user == bet.winner ? " bet-winner" : (" bet-loser" if bet.finished?) %>">
              <% if bet.user == bet.winner %>
                <i class="fa-solid fa-crown position-absolute bet-winner-crown" style="color: #e9cd16;"></i>
              <% end %>
              <%= cl_image_tag(bet.user.photo.key, class: "avatar") if bet.user.photo.key.present? %>
              <p class="m-0"><strong><%= bet.user.name %></strong></p>
            </div>
          </div>
          <div class="col-2 text-center align-self-center position-relative">
            <i class="fa-solid fa-bolt" style="color: #FFDE59;font-size: 35px"></i>
          </div>
          <div class="col-5 d-flex align-items-center justify-content-center gap-2">
            <div class="position-relative text-center<%= bet.opponent == bet.winner ? " bet-winner" : (" bet-loser" if bet.finished?) %>">
              <% if bet.opponent == bet.winner %>
                <i class="fa-solid fa-crown position-absolute bet-winner-crown" style="color: #e9cd16;"></i>
              <% end %>
              <%= cl_image_tag(bet.opponent.photo.key, class: "avatar") if bet.opponent.photo.key.present? %>
              <p class="m-0"><strong><%= bet.opponent.name %></strong></p>
            </div>
          </div>
          <div class="border bet-title">
            <h4 class="m-0"><strong><%= bet.name %></strong></h4>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <p class="text-center m-0" style="font-size: 15px"><i class="fa-regular fa-hourglass-half"></i> <span data-controller="timer" data-timer-endtime-value="<%= bet.active? ? bet.end_time : 0 %>" data-timer-target='span'></span></p>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <p class="text-center bet-date bet-stake">
              <i class="fa-solid fa-award"></i>
              Stakes:  <%= bet.stake %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
    <% if (current_user.received_pending_bets.where(id: bet.id).present? if current_user) && action_name == "profile" %>
      <div class="bet-actions-btns">
        <%= link_to bet_accept_path(bet), class: "bet-accept-btn", data: { turbo_method: :post } do %>
          <i class="fa-solid fa-circle-check"></i>
        <% end %>
        <%= link_to bet_deny_path(bet), class: "bet-deny-btn", data: { turbo_method: :post } do %>
          <i class="fa-solid fa-circle-xmark"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/bets/_info_window.html.erb
<div class="rounded-2">
  <h2><%= bet.name %></h2>
  <hr>
  <div>
    <p><i class="fa-solid fa-user"></i> <strong>User:</strong> <%= bet.user.name %></p>
    <p>VS.</p>
    <p><i class="fa-regular fa-user"></i> <strong>User:</strong> <%= bet.opponent.name %></p>
  </div>
  <hr>
  <div class="text-start">
    <p><i class="fa-solid fa-sack-dollar"></i> <strong>Stake:</strong> <%= bet.stake %></p>
    <i class="fa-regular fa-hourglass-half"></i> <span data-controller="timer" data-timer-endtime-value="<%= bet.end_time %>" data-timer-target='span'></span>
  </div>
</div>

app/views/bets/around_me.html.erb
<div class="mt-3 mb-2">
  <h3 class="custom-bg-info mb-2 mx-auto text-center"><strong>Bets Around Me</strong></h3>
</div>

<div class="map-in-center mt-4"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div class="container footer-bottom-margin bets-container content pb-5">
  <% @bets.each do |bet| %>
    <div class="bet-card">
      <%= render "bet_card", bet: bet %>
    </div>
    <div class="card-space"></div>
  <% end %>
</div>

app/views/bets/index.html.erb
<div class="container">
  <h2 class="custom-bg-info p-1 mx-auto mt-3 text-center"><strong>Top Bets   </strong><i class="fa-solid fa-trophy" style="color: #f3b853;"></i></h2>

  <div class="footer-bottom-margin bets-container content pb-5">
    <% @bets.each do |bet| %>
      <div class="bet-card">
        <%= render "bet_card", bet: bet %>
      </div>
      <div class="card-space"></div>
    <% end %>
  </div>
</div>

app/views/bets/multiform_step_1.html.erb
<div class="page-wrapper" style="max-width: 400px; margin-top: 100px">
  <div class=" container container-form align-middle justify-content-center footer-bottom-margin">
      <%= simple_form_for(@bet) do |f| %>
        <div class="text-center mt-4 mb-4">
          <h1 class="text-underline font-weight-bold"> Let's Dare2Bet </h1>
          <h2> Just enter some details </h2>
        </div>
        <div class="mt-2 mb-5 ">
          <div class="progress">
            <div class="progress-bar bg-secondary progress-bar-striped progress-bar-animated" role="progressbar" style="width: 5%" aria-valuenow="5" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
        </div>


      <%= f.input :name, label: "Name of the bet : (max 16)", maxlength: 16, input_html: { autocomplete: "off" } %>
        <%= f.input :opponent_id, as: :text, input_html: { data: {controller: "opponent-search"}}  %>

        <%#= f.association :opponent, include_blank: false, include_hidden: false, label: "Select your beter :" %>

        <div class="text-center mt-5">
          <%= f.submit "Go to next step", class: "btn btn-violet" %>
        </div>
      <% end %>
  </div>
</div>

app/views/bets/multiform_step_2.html.erb
<div class="page-wrapper" style="max-width: 400px; margin-top: 100px">
<div class=" container container-form align-middle  justify-content-center footer-bottom-margin w-100">
 <%= simple_form_for(@bet, step_2: true) do |f| %>
    <div class="text-center mt-4 mb-4">
      <h2 class="text-underline font-weight-bold"> Add some more details </h2>
    </div>
    <div class="mt-2 mb-5 ">
      <div class="progress">
        <div class="progress-bar bg-secondary progress-bar-striped progress-bar-animated" role="progressbar" style="width: 33%" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
    </div>


    <%= f.input :stake, input_html: { autocomplete: "off" } %>
    <%= f.input :location, input_html: { autocomplete: "off" } %>
    <%= f.input :end_time, html5: true %>
    <input  type="hidden" name="step_2" value="true" >

    <div class="text-center mt-5">
      <%= f.submit "Go to next step", class: "btn btn-violet" %>
    </div>
  <% end %>
</div>
</div>

app/views/bets/multiform_step_3.html.erb
<div class="page-wrapper" style="max-width: 400px; margin-top: 100px">
<div class=" container container-form align-middle  justify-content-center footer-bottom-margin w-100">
   <%= simple_form_for(@bet) do |f| %>
    <div class="text-center mt-4 mb-4">
      <h1 class="text-underline font-weight-bold"> Last step </h1>
    </div>
    <div class="mt-2 mb-5 ">
      <div class="progress">
        <div class="progress-bar bg-secondary progress-bar-striped progress-bar-animated" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
    </div>

    <%= f.input :privacy, collection: ["public", "private"] %>
    <%= f.association :tag %>

    <div class="text-center mt-5">
      <%= f.submit "Create the bet", class: "btn btn-violet" %>
    </div>
  <% end %>
</div>
</div>

app/views/bets/my_bets.html.erb
<div class="container">
    <div class="footer-bottom-margin bets-container text-center mt-2">
      <div class="d-flex flex-column align-items-center">
        <h3 class="custom-bg-primary mb-2 mt-3 mx-auto text-center"><strong>My Active Bets</strong></h3>
      </div >
        <div>
          <% @active_bets.each do |bet| %>
            <div class="mt-4">
              <%= render "bet_card", bet: bet %>
            </div>
          <% end %>
        </div>
      <div class="mt-3 mb-2">
        <h3 class="custom-bg-info mb-2 mt-5 mx-auto text-center"><strong>Past Bets</strong></h3>
      </div>
      <div class="footer-bottom-margin">
        <% @past_bets.each do |bet| %>
          <div class="mt-4">
            <%= render "bet_card", bet: bet %>
          </div>
        <% end %>

      </div>
  </div>
</div>

app/views/bets/new.html.erb
<div class=" container d-flex justify-content-center vh-50 mt-1 footer-bottom-margin">
  <%= simple_form_for(@bet) do |f| %>
  <h2> Members </h2>
    <%= f.input :name %>
    <%= f.association :users, include_blank: false, include_hidden: false %>

    <h2> Bet's info </h2>
    <%= f.input :stake %>
    <%= f.input :location %>
     <%= f.input :end_time, html5: true %>

    <h2> Bet's privacy </h2>
    <%= f.input :privacy, collection: ["public", "private"], selected: "private" %>
    <%= f.association :tag %>
    <%= f.submit  class: "btn btn-dark btn-block" %>
  <% end %>
</div>

app/views/bets/resolve.html.erb
<div class="mt-4 mb-2">
  <h3 class="custom-bg-info mb-2 mx-auto text-center"><strong>Who won the bet?</strong></h3>
</div>

<div class="container d-flex justify-content-center vh-50 mt-5 footer-bottom-margin">
  <%= simple_form_for @bet, url: bet_set_result_path(@bet) do |f| %>
    <%= f.input :winner_id,
                collection: [@bet.user, @bet.opponent],
                class: 'form-control',
                label: "<i class='fa-solid fa-crown' style='color: #e9cd16;'></i> Winner".html_safe,
                label_html: { class: "fw-bold" } %>
    <%= f.submit "Settle!", id: "confirm-button", class: "bet-resolve-btn btn-block" %>
  <% end %>
</div>

app/views/bets/show.html.erb
<div class="container">
  <div class="bet-card-shadow rounded-4 position-relative align-items-center justify-content-center text-center mt-3 footer-bottom-margin">
    <div class="col bet-card text-start  ">
      <%= render "bet_card", bet: @bet %>

      <div class="border-top-0 inner-border rounded-bottom-4 position-relative">
        <div class="d-flex justify-content-between mb-2">
          <div class="d-flex gap-1 align-items-center">
            <div style="background: <%= @bet.active? ? "green" : "#d10101" %>; width: 10px; height: 10px; border-radius: 50%"></div>
            <p class="mb-0" style="color: <%= @bet.active? ? "green" : "#d10101" %>; font-size: 16px"><%= @bet.status %></p>
          </div>
          <p class="bet-privacy mb-0"><strong>
            <% if  @bet.privacy == "public" %>
              <i class="fa-solid fa-unlock"></i></strong>
            <% else %>
              <i class="fa-solid fa-lock"></i></strong>
            <% end %>
            <%= @bet.privacy %>
          </p>

        </div>
        <p class="d-flex gap-2">
          <strong><i class="fa-solid fa-location-dot text-center" style="color: #8c50f7; width: 20px"></i></strong>
          <%= @bet.location %>
        </p>
        <hr>
        <p class="text-center mb-1" style="color: #8c50f7">
          <i class="fa-solid fa-cake-candles"></i> <strong>Created on</strong>
        </p>
        <p class="text-center">
          <%= @bet.created_at.strftime("%d %b %Y") %>
        </p>
        <p class="text-center mb-1" style="color: #8c50f7">
          <i class="fa-regular fa-calendar-plus text-center"></i> <strong>Expires on</strong>
        </p>
        <p class="text-center">
          <%= @bet.end_time.strftime("%d %b %Y") %>
        </p>
      </div>
    </div>

    <% if (current_user == @bet.user || current_user == @bet.opponent) && @bet.active? %>
      <div class="d-flex gap-4 justify-content-center gap-4 position-absolute bet-resolve-btns-container" >
        <%= link_to bet_resolve_path(@bet), class: "bet-card-shadow bet-resolve-btn gap-2"  do %>
          <i class="fa-solid fa-trophy"></i> Resolve
        <% end %>

        <%= link_to bet_path(@bet), class: "bet-card-shadow bet-delete-btn gap-2", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-regular fa-trash-can"></i> Delete
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.bootstrap5.css" rel="stylesheet">

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>


  <body>
    <% unless action_name == "home" || (action_name == "new" && controller_name == "sessions")  %>
      <%= render "shared/navbar" %>
    <% end %>

    <%= render "shared/flashes" %>

    <%= yield %>

    <% unless action_name == "home" || (action_name == "new" && controller_name == "sessions")  %>
      <footer class="footer">
        <%= render "shared/footer" %>
      </footer>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner pt-5">
  <%= image_tag "Dare2betpurple.gif" %>
  <div class="container centered-banner-text">
    <div class="ps-5 my-auto">
      <p class="banner-info d-flex gap-2 text-start"><i class="fa-regular fa-handshake text-center" style="color: #f5d847;"></i><span>Challenge your friends</span></p>
      <p class="banner-info d-flex gap-2 text-start"><i class="fa-solid fa-users-between-lines text-center" style="color: #f5d847;"></i><span>Make your bets public</span></p>
      <p class="banner-info d-flex gap-2 text-start"><i class="fa-solid fa-ghost text-center" style="color: #f5d847;"></i><span>No more empty bets!</span></p>
    </div>
  </div>
  <div class="homepage-buttons text-center">
    <%= link_to "Join the fun!", new_user_session_path, class: "btn btn-outline-light join-fun-btn mb-0" %>
  </div>
</div>

<div class="container center-content" id="homepage-cards">
  <div class="col">
    <h3 class="mt-4 custom-bg-info mb-2 mx-auto text-center"><strong>Bets Around Me</strong></h3>
    <% @bets.each do |bet| %>
      <div class="col">
      <%= render "bets/bet_card", bet: bet %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer footer--icons text-center p-3 px-4">
        <%= link_to bets_path, class: "text-decoration-none color-item" do %>
        <i class="fa-solid fa-medal"></i>
        <% end %>
        <%= link_to around_me_path, class: "text-decoration-none color-item" do %>
        <i class="fa-solid fa-location-dot "></i>
        <% end %>
        <%= link_to multiform_step_1_bets_path, class: "text-decoration-none text-white" do %>

        <i class="fa-solid fa-circle-plus" id="circle"></i>
        <% end %>
        <%= link_to my_bets_path, class: "text-decoration-none color-item" do %>
        <i class="fa-solid fa-list"></i>
        <% end %>
        <%= link_to profile_path, class: "text-decoration-none color-item" do %>
          <i class="fa-solid fa-gear"></i>
        <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon position-relative", id="height">
  <% unless action_name == "index" %>
    <%= link_to "javascript:history.back()", class: "bg-white text-white btn ms-4" do %>
      <i class="fa-solid fa-angle-left no-hover" style="color: #8c50f7;"></i>
    <% end %>
  <% end %>

  <%= link_to my_bets_path, class: "navbar-brand mx-auto" do %>
    <%= image_tag "pigpurple.png", alt:"Dare Bet fancy logo", class:"navlogo position-absolute" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="text-center mt-3">
<h1>Edit your details </h1>
</div>

app/views/users/profile.html.erb
<div class="container">
  <h1 class="custom-bg-primary pb-5 mt-3 mx-auto text-center"><strong>My Profile</strong></h1>
  <div class="container position-relative mt-5">
    <div class="user-profile-details-box mx-auto position-relative" style="width: 90%;">
      <div class="profile-purple">
        <%= link_to edit_user_registration_path, class: "position-absolute", style: "right: 16px; top: 12px; font-size: 24px;" do %>
        <i class="fa-solid fa-pen-to-square text-white"></i>
        <% end %>
        <h3 class="text-center mt-5 mb-1 fw-bold" style="color: white; padding-top: 34px;"><%= current_user.name %></h3>
        <p class="text-white text-center" style="font-size: 16px"><%= current_user.email %></p>
      </div>

      <%= cl_image_tag(current_user.photo.key, class: "avatar-large position-absolute avatar-profile") if current_user.photo.present? %>

      <div class="mt-5" style="padding-top: 100px">
        <div class="d-flex gap-2 mb-2">
          <i class="fa-solid fa-location-dot" style="color: #8c50f7; align-self: center; width: 20px"></i>
          <p class="mb-0"><%= current_user.location %></p>
        </div>
        <div class="d-flex gap-2">
          <i class="fa-solid fa-cake-candles" style="color: #8c50f7; align-self: center; width: 20px"></i>
          <p class="mb-0"><strong>Daring to Bet since:</strong></p>
        </div>
        <p style="margin-left: 27px !important;"><%= current_user.created_at.strftime("%d %b %Y") %></p>
      </div>
      <div class="text-center">
        <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-violet-border text-decoration-none d-block" do %>
          <i class="fa-solid fa-right-to-bracket"></i>
          Log Out
        <% end %>
      </div>
    </div>
  </div>

  <%# <div class="user-profile-details-box"> %>

  <div class="footer-bottom-margin">
    <div class="mt-3 mb-2">
      <h3 class="custom-bg-info mb-2 mt-5 mx-auto text-center"><strong>Received Pending Bets</strong></h3>
    </div>
    <div>
      <% if @received_pending_bets.present? %>
        <% @received_pending_bets.each do |bet| %>
          <div class="mt-4 pb-4">
            <%= render "bets/bet_card", bet: bet %>
          </div>
        <% end %>
      <% else %>
        <p class="text-center">You haven't received any new bets.</p>
      <% end %>
    </div>
    <div class="mt-3 mb-2">
      <h3 class="custom-bg-info mb-2 mt-5 mx-auto text-center"><strong>Sent Bets</strong></h3>
    </div>
    <div class="footer-bottom-margin">
      <% if @sent_pending_bets.present? %>
        <% @sent_pending_bets.each do |bet| %>
          <div class="mt-4">
            <%= render "bets/bet_card", bet: bet %>
          </div>
        <% end %>
      <% else %>
        <p class="text-center">No sent bets.</p>
      <% end %>
    </div>
  </div>
</div>